// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: internal/hotel/search.proto

package hotel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchHotelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InDate   string `protobuf:"bytes,1,opt,name=InDate,proto3" json:"InDate,omitempty"`
	OutDate  string `protobuf:"bytes,2,opt,name=OutDate,proto3" json:"OutDate,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`
}

func (x *SearchHotelsRequest) Reset() {
	*x = SearchHotelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_hotel_search_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelsRequest) ProtoMessage() {}

func (x *SearchHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hotel_search_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelsRequest.ProtoReflect.Descriptor instead.
func (*SearchHotelsRequest) Descriptor() ([]byte, []int) {
	return file_internal_hotel_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchHotelsRequest) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *SearchHotelsRequest) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

func (x *SearchHotelsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type SearchHotelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*HotelProfile `protobuf:"bytes,1,rep,name=Profiles,proto3" json:"Profiles,omitempty"`
}

func (x *SearchHotelsResponse) Reset() {
	*x = SearchHotelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_hotel_search_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelsResponse) ProtoMessage() {}

func (x *SearchHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hotel_search_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelsResponse.ProtoReflect.Descriptor instead.
func (*SearchHotelsResponse) Descriptor() ([]byte, []int) {
	return file_internal_hotel_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHotelsResponse) GetProfiles() []*HotelProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type NearbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InDate   string `protobuf:"bytes,1,opt,name=InDate,proto3" json:"InDate,omitempty"`
	OutDate  string `protobuf:"bytes,2,opt,name=OutDate,proto3" json:"OutDate,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`
}

func (x *NearbyRequest) Reset() {
	*x = NearbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_hotel_search_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyRequest) ProtoMessage() {}

func (x *NearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hotel_search_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyRequest.ProtoReflect.Descriptor instead.
func (*NearbyRequest) Descriptor() ([]byte, []int) {
	return file_internal_hotel_search_proto_rawDescGZIP(), []int{2}
}

func (x *NearbyRequest) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *NearbyRequest) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

func (x *NearbyRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type NearbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rates []*Rate `protobuf:"bytes,1,rep,name=Rates,proto3" json:"Rates,omitempty"`
}

func (x *NearbyResponse) Reset() {
	*x = NearbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_hotel_search_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyResponse) ProtoMessage() {}

func (x *NearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hotel_search_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyResponse.ProtoReflect.Descriptor instead.
func (*NearbyResponse) Descriptor() ([]byte, []int) {
	return file_internal_hotel_search_proto_rawDescGZIP(), []int{3}
}

func (x *NearbyResponse) GetRates() []*Rate {
	if x != nil {
		return x.Rates
	}
	return nil
}

type HotelProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId string `protobuf:"bytes,1,opt,name=HotelId,proto3" json:"HotelId,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone   string `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Info    string `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *HotelProfile) Reset() {
	*x = HotelProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_hotel_search_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotelProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelProfile) ProtoMessage() {}

func (x *HotelProfile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hotel_search_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelProfile.ProtoReflect.Descriptor instead.
func (*HotelProfile) Descriptor() ([]byte, []int) {
	return file_internal_hotel_search_proto_rawDescGZIP(), []int{4}
}

func (x *HotelProfile) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *HotelProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HotelProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *HotelProfile) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type Rate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId string `protobuf:"bytes,1,opt,name=HotelId,proto3" json:"HotelId,omitempty"`
	Price   int32  `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
}

func (x *Rate) Reset() {
	*x = Rate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_hotel_search_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hotel_search_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_internal_hotel_search_proto_rawDescGZIP(), []int{5}
}

func (x *Rate) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *Rate) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_internal_hotel_search_proto protoreflect.FileDescriptor

var file_internal_hotel_search_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c,
	0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x22, 0x63, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49,
	0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x75, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x14, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x22, 0x5d, 0x0a, 0x0d, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f,
	0x75, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x75,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x33, 0x0a, 0x0e, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x52, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x52, 0x61, 0x74, 0x65, 0x73, 0x22, 0x66, 0x0a, 0x0c, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x36,
	0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32, 0x8f, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x12, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x06, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x12, 0x14, 0x2e, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x2e, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x69, 0x61, 0x6c, 0x69, 0x2d, 0x58, 0x69, 0x6e,
	0x67, 0x2f, 0x6d, 0x75, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_hotel_search_proto_rawDescOnce sync.Once
	file_internal_hotel_search_proto_rawDescData = file_internal_hotel_search_proto_rawDesc
)

func file_internal_hotel_search_proto_rawDescGZIP() []byte {
	file_internal_hotel_search_proto_rawDescOnce.Do(func() {
		file_internal_hotel_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_hotel_search_proto_rawDescData)
	})
	return file_internal_hotel_search_proto_rawDescData
}

var file_internal_hotel_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_hotel_search_proto_goTypes = []interface{}{
	(*SearchHotelsRequest)(nil),  // 0: hotel.SearchHotelsRequest
	(*SearchHotelsResponse)(nil), // 1: hotel.SearchHotelsResponse
	(*NearbyRequest)(nil),        // 2: hotel.NearbyRequest
	(*NearbyResponse)(nil),       // 3: hotel.NearbyResponse
	(*HotelProfile)(nil),         // 4: hotel.HotelProfile
	(*Rate)(nil),                 // 5: hotel.Rate
}
var file_internal_hotel_search_proto_depIdxs = []int32{
	4, // 0: hotel.SearchHotelsResponse.Profiles:type_name -> hotel.HotelProfile
	5, // 1: hotel.NearbyResponse.Rates:type_name -> hotel.Rate
	0, // 2: hotel.SearchService.SearchHotels:input_type -> hotel.SearchHotelsRequest
	2, // 3: hotel.SearchService.Nearby:input_type -> hotel.NearbyRequest
	1, // 4: hotel.SearchService.SearchHotels:output_type -> hotel.SearchHotelsResponse
	3, // 5: hotel.SearchService.Nearby:output_type -> hotel.NearbyResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_hotel_search_proto_init() }
func file_internal_hotel_search_proto_init() {
	if File_internal_hotel_search_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_hotel_search_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchHotelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_hotel_search_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchHotelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_hotel_search_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_hotel_search_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_hotel_search_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotelProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_hotel_search_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_hotel_search_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_hotel_search_proto_goTypes,
		DependencyIndexes: file_internal_hotel_search_proto_depIdxs,
		MessageInfos:      file_internal_hotel_search_proto_msgTypes,
	}.Build()
	File_internal_hotel_search_proto = out.File
	file_internal_hotel_search_proto_rawDesc = nil
	file_internal_hotel_search_proto_goTypes = nil
	file_internal_hotel_search_proto_depIdxs = nil
}
